language: python
python:
  - "3.6"
before_install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  - pip install dataclasses
  - pip install requests
  - pip install .
before_script:
  - pip install requests-mock
  - pip install pytest-cov
  - pip install codecov
script:
  - pytest --cov=nhl tests/
after_success:
  - codecov
